# Generated by Django 4.0.3 on 2022-04-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formcontacts',
            new_name='storage',
        ),
    ]
