# Generated by Django 4.0.3 on 2022-04-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_formcontacts_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='phone',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='lname',
            new_name='uname',
        ),
    ]
