# Generated by Django 4.0.3 on 2022-04-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_phone_storage_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='storage',
            new_name='signup',
        ),
    ]
