# Generated by Django 4.0.3 on 2022-04-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_storage_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='sign',
        ),
    ]
