# Generated by Django 4.0.3 on 2022-05-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jewel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
