# Generated by Django 4.0.3 on 2022-05-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sign_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='images/profiles'),
        ),
    ]
