# Generated by Django 4.0.3 on 2022-05-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_sign_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('curl', models.CharField(max_length=100)),
                ('cprice', models.IntegerField(default=0, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sign',
            name='profile_pic',
            field=models.ImageField(default='images/profiles/default.png', upload_to='images/profiles'),
        ),
    ]
