# Generated by Django 4.0.3 on 2022-05-20 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cart_alter_sign_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewel',
            name='jname',
        ),
    ]
