# Generated by Django 4.0.3 on 2022-05-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_jewel_jname'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewel',
            name='jname',
            field=models.CharField(default='jewel', max_length=100),
            preserve_default=False,
        ),
    ]
