# Generated by Django 4.0.3 on 2022-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_jewel_jname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icname', models.CharField(max_length=100)),
                ('icurl', models.CharField(max_length=500)),
                ('icprice', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
