# Generated by Django 4.0.3 on 2022-05-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_itemcart_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
