# Generated by Django 4.0.3 on 2022-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_jewel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='address',
            field=models.CharField(default='Your address', max_length=200),
        ),
        migrations.AddField(
            model_name='sign',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='gender',
            field=models.CharField(default='gender', max_length=100),
            preserve_default=False,
        ),
    ]
